apiVersion: v1
kind: Service
metadata:
  name: example-service
  namespace: default
spec: 
  ports:
    - name: test
      protocol: TCP
      port: 666
      targetPort: 666
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: application-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: pipeline.llocal.host
      http:
        paths:
          - path: /stage-frontend
            backend:
              serviceName: stage-frontend-service
              servicePort: 80

