---
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: build-and-push-run
  namespace: tekton-pipeline-1
spec:
  taskRef:
    name: build-and-push
  params:
    - name: image-name
      value: "voorbeeldnaam"
    - name: version
      value: "voorbeeldversion"
  workspaces:
    - name: source
      persistentVolumeClaim:
        claimName: workspace

  serviceAccountName: service-acc