---
# https://medium.com/@nikhilthomas1/cloud-native-cicd-on-openshift-with-openshift-pipelines-tektoncd-pipelines-part-3-github-1db6dd8e8ca7
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: create-repo-webhook-backend
  namespace: tekton-pipeline-1
spec:
  taskRef:
    name: create-webhook
  inputs:
    params:
    - name: GitHubOrg
      value: "beppevanrolleghem"
    - name: GitHubUser
      value: "beppevanrolleghem"
    - name: GitHubRepo
      value: "stage-backend"
    - name: GitHubSecretName
      value: github-secret
    - name: GitHubAccessTokenKey
      value: token
    - name: GitHubSecretStringKey
      value: secret
    - name: ExternalDomain
      value: "35.189.243.0:8080"
  timeout: 1000s
  serviceAccountName: service-acc