
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: event-listener-github
  namespace: tekton-pipeline-1
spec:
  serviceAccountName: service-acc
  triggers:
    - name: github
      interceptors:
        - github:
            eventTypes: 
              - pull_request
              - push
      bindings:
        - name: github-trigger-binding
      template:
        name: github-trigger-template
---
apiVersion: v1
kind: Service
metadata:
  name: github-event-listener
  namespace: tekton-pipeline-1
spec:
  type: NodePort
  selector:
    eventlistener: event-listener-github
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: event-listener-gitlab
  namespace: tekton-pipeline-1
spec:
  serviceAccountName: service-acc
  triggers:
    - name: gitlab
      interceptors:
        - gitlab:
            eventTypes:
              - Push Hook
      bindings:
        - name: gitlab-trigger-binding
      template:
        name: github-trigger-template
---
apiVersion: v1
kind: Service
metadata:
  name: gitlab-event-listener
  namespace: tekton-pipeline-1
spec:
  type: NodePort
  selector:
    eventlistener: event-listener-gitlab
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: event-listener-infra
  namespace: tekton-pipeline-1
spec:
  serviceAccountName: service-acc
  triggers:
    - name: github
      interceptors:
        - github:
            eventTypes: 
              - pull_request
              - push
      bindings:
        - name: github-trigger-binding
      template:
        name: infra-trigger-template
    - name: gitlab
      interceptors:
        - gitlab:
            eventTypes:
              - Push Hook
      bindings:
        - name: gitlab-trigger-binding
      template:
        name: infra-trigger-template
---
apiVersion: v1
kind: Service
metadata:
  name: infra-event-listener
  namespace: tekton-pipeline-1
spec:
  type: NodePort
  selector:
    eventlistener: event-listener-infra
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: event-listener-ingress
  namespace: tekton-pipeline-1
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: pipeline.llocal.host
      http:
        paths:
          - path: /stage-github
            backend:
              serviceName: el-event-listener-github
              servicePort: 8080
          - path: /stage-gitlab
            backend:
              serviceName: el-event-listener-gitlab
              servicePort: 8080
          - path: /stage-infra
            backend:
              serviceName: el-event-listener-infra
              servicePort: 8080
          - path: /stage-test
            backend:
              serviceName: test-service
              servicePort: 8080