
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: github-event-listener
spec:
  serviceAccountName: service-acc
  triggers:
    - name: github
      # interceptors:
      #   - github:
      #       eventTypes:
      #         - pull_request
      #         - push
      bindings:
        - name: github-trigger-binding
      template:
        name: github-trigger-template

---
apiVersion: v1
kind: Service
metadata:
  name: manual-service
spec:
  ports:
  - name: http-listener
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: github-event-listener
  type: LoadBalancer