---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: github-trigger-binding
  namespace: tekton-pipeline-1
spec:
  params:
  - name: gitrevision
    value: "$(body.head_commit.id)"
  - name: gitrepositoryurl
    value: "$(body.repository.clone_url)"
  - name: gitreponame
    value: $(body.repository.name)
  - name: branch
    value: $(body.repository.default_branch)
  - name: gitrepofullname
    value: $(body.repository.full_name)