---
apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: github-trigger-template
spec:
  params:
    - name: gitrevision
      description: The git revision
      default: master
    - name: gitrepositoryurl
      description: The git repository url
    - name: gitreponame
      description: the name of the git repository
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        name: application-pipeline-run
      spec:
        serviceAccountName: service-acc
        pipelineRef:
          name: stage-application-pipeline
        workspaces:
        - name: workspace
          persistentVolumeClaim:
            claimName: workspace
        params:
          - name: git-url
            value: $(inputs.params.gitrepositoryurl)
          - name: branch
            value: $(inputs.params.gitrevision)
          - name: git-repo-name
            value: $(inputs.params.gitreponame)