---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: github-trigger-binding
spec:
  params:
  - name: gitrevision
    value: $(body.repository.default_branch)
  - name: gitrepositoryurl
    value: $(body.repository.clone_url)
  - name: gitreponame
    value: $(body.repository.name)