---
apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: github-trigger-template
  namespace: tekton-pipeline-1
spec:
  params:
    - name: gitrevision
      description: The git revision
      default: master
    - name: gitrepositoryurl
      description: The git repository url
    - name: gitreponame
      description: the name of the git repository
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        generateName: github-pipeline-run-
      spec:
        serviceAccountName: service-acc
        pipelineRef:
          name: stage-application-pipeline
        Timeout: "2h30m00s"
        workspaces:
        - name: workspace
          persistentVolumeClaim:
            claimName: workspace
        params:
          - name: git-url
            value: $(params.gitrepositoryurl)
          - name: branch
            value: $(params.gitrevision)
          - name: git-repo-name
            value: $(params.gitreponame)